baseURL = 'https://sciencequests.com/'
languageCode = 'en-us'
title = 'Science for 7-12 year olds made more fun and relatable | Aligned with leading school curricula | Action-packed stories, games and quizzes to improve understanding | ScienceQuests'
theme = 'basic'

googleAnalytics = 'G-4EHNRV42PM'

[params]
  description = 'Reimagining science for 7-12 year olds'
  images = ['sq-open-graph.png']
  title = 'Science for 7-12 year olds made more fun and relatable | Aligned with leading school curricula | Action-packed stories, games and quizzes to improve understanding | ScienceQuests'
[taxonomies]
  series = 'series'
